//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionLaunch.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.12.0.0")]
    internal sealed partial class Device1 : global::System.Configuration.ApplicationSettingsBase {
        
        private static Device1 defaultInstance = ((Device1)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Device1())));
        
        public static Device1 Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool D1Present {
            get {
                return ((bool)(this["D1Present"]));
            }
            set {
                this["D1Present"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Force lasting 1")]
        public string D1Name {
            get {
                return ((string)(this["D1Name"]));
            }
            set {
                this["D1Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("size")]
        public string D1Param1Name {
            get {
                return ((string)(this["D1Param1Name"]));
            }
            set {
                this["D1Param1Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ND")]
        public string D1Param2Name {
            get {
                return ((string)(this["D1Param2Name"]));
            }
            set {
                this["D1Param2Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string D1Param3Name {
            get {
                return ((string)(this["D1Param3Name"]));
            }
            set {
                this["D1Param3Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string D1Param4Name {
            get {
                return ((string)(this["D1Param4Name"]));
            }
            set {
                this["D1Param4Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool D1Param1On {
            get {
                return ((bool)(this["D1Param1On"]));
            }
            set {
                this["D1Param1On"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool D1Param2On {
            get {
                return ((bool)(this["D1Param2On"]));
            }
            set {
                this["D1Param2On"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool D1Param3On {
            get {
                return ((bool)(this["D1Param3On"]));
            }
            set {
                this["D1Param3On"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool D1Param4On {
            get {
                return ((bool)(this["D1Param4On"]));
            }
            set {
                this["D1Param4On"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int D1Mode {
            get {
                return ((int)(this["D1Mode"]));
            }
            set {
                this["D1Mode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool D1WithRecipe {
            get {
                return ((bool)(this["D1WithRecipe"]));
            }
            set {
                this["D1WithRecipe"] = value;
            }
        }
    }
}
