//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionLaunch.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.12.0.0")]
    internal sealed partial class Device3 : global::System.Configuration.ApplicationSettingsBase {
        
        private static Device3 defaultInstance = ((Device3)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Device3())));
        
        public static Device3 Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool D3Present {
            get {
                return ((bool)(this["D3Present"]));
            }
            set {
                this["D3Present"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Controllo colla")]
        public string D3Name {
            get {
                return ((string)(this["D3Name"]));
            }
            set {
                this["D3Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("qt. nominale (gr)")]
        public string D3Param1Name {
            get {
                return ((string)(this["D3Param1Name"]));
            }
            set {
                this["D3Param1Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("tolleranza (gr)")]
        public string D3Param2Name {
            get {
                return ((string)(this["D3Param2Name"]));
            }
            set {
                this["D3Param2Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string D3Param3Name {
            get {
                return ((string)(this["D3Param3Name"]));
            }
            set {
                this["D3Param3Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string D3Param4Name {
            get {
                return ((string)(this["D3Param4Name"]));
            }
            set {
                this["D3Param4Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool D3Param1On {
            get {
                return ((bool)(this["D3Param1On"]));
            }
            set {
                this["D3Param1On"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool D3Param2On {
            get {
                return ((bool)(this["D3Param2On"]));
            }
            set {
                this["D3Param2On"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool D3Param3On {
            get {
                return ((bool)(this["D3Param3On"]));
            }
            set {
                this["D3Param3On"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool D3Param4On {
            get {
                return ((bool)(this["D3Param4On"]));
            }
            set {
                this["D3Param4On"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int D3Mode {
            get {
                return ((int)(this["D3Mode"]));
            }
            set {
                this["D3Mode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("qt. applicata (gr)")]
        public string C3Param1Name {
            get {
                return ((string)(this["C3Param1Name"]));
            }
            set {
                this["C3Param1Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool C3Param1On {
            get {
                return ((bool)(this["C3Param1On"]));
            }
            set {
                this["C3Param1On"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string C3Param2Name {
            get {
                return ((string)(this["C3Param2Name"]));
            }
            set {
                this["C3Param2Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool C3Param2On {
            get {
                return ((bool)(this["C3Param2On"]));
            }
            set {
                this["C3Param2On"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool D3WithRecipe {
            get {
                return ((bool)(this["D3WithRecipe"]));
            }
            set {
                this["D3WithRecipe"] = value;
            }
        }
    }
}
