//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionLaunch.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.12.0.0")]
    internal sealed partial class Device2 : global::System.Configuration.ApplicationSettingsBase {
        
        private static Device2 defaultInstance = ((Device2)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Device2())));
        
        public static Device2 Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool D2Present {
            get {
                return ((bool)(this["D2Present"]));
            }
            set {
                this["D2Present"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Force lasting 2")]
        public string D2Name {
            get {
                return ((string)(this["D2Name"]));
            }
            set {
                this["D2Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("size")]
        public string D2Param1Name {
            get {
                return ((string)(this["D2Param1Name"]));
            }
            set {
                this["D2Param1Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string D2Param2Name {
            get {
                return ((string)(this["D2Param2Name"]));
            }
            set {
                this["D2Param2Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string D2Param3Name {
            get {
                return ((string)(this["D2Param3Name"]));
            }
            set {
                this["D2Param3Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string D2Param4Name {
            get {
                return ((string)(this["D2Param4Name"]));
            }
            set {
                this["D2Param4Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool D2Param1On {
            get {
                return ((bool)(this["D2Param1On"]));
            }
            set {
                this["D2Param1On"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool D2Param2On {
            get {
                return ((bool)(this["D2Param2On"]));
            }
            set {
                this["D2Param2On"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool D2Param3On {
            get {
                return ((bool)(this["D2Param3On"]));
            }
            set {
                this["D2Param3On"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool D2Param4On {
            get {
                return ((bool)(this["D2Param4On"]));
            }
            set {
                this["D2Param4On"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int D2Mode {
            get {
                return ((int)(this["D2Mode"]));
            }
            set {
                this["D2Mode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("tara (gr)")]
        public string C2Param1Name {
            get {
                return ((string)(this["C2Param1Name"]));
            }
            set {
                this["C2Param1Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("p. lordo (gr)")]
        public string C2Param2Name {
            get {
                return ((string)(this["C2Param2Name"]));
            }
            set {
                this["C2Param2Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool C2Param1On {
            get {
                return ((bool)(this["C2Param1On"]));
            }
            set {
                this["C2Param1On"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool C2Param2On {
            get {
                return ((bool)(this["C2Param2On"]));
            }
            set {
                this["C2Param2On"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool D2WithRecipe {
            get {
                return ((bool)(this["D2WithRecipe"]));
            }
            set {
                this["D2WithRecipe"] = value;
            }
        }
    }
}
