//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionLaunch.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.12.0.0")]
    internal sealed partial class Device4 : global::System.Configuration.ApplicationSettingsBase {
        
        private static Device4 defaultInstance = ((Device4)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Device4())));
        
        public static Device4 Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool D4Present {
            get {
                return ((bool)(this["D4Present"]));
            }
            set {
                this["D4Present"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Delasting")]
        public string D4Name {
            get {
                return ((string)(this["D4Name"]));
            }
            set {
                this["D4Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("tipo di movimento")]
        public string D4Param1Name {
            get {
                return ((string)(this["D4Param1Name"]));
            }
            set {
                this["D4Param1Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("p. scalzata (bar)")]
        public string D4Param2Name {
            get {
                return ((string)(this["D4Param2Name"]));
            }
            set {
                this["D4Param2Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("t. pos. pinza (msec)")]
        public string D4Param3Name {
            get {
                return ((string)(this["D4Param3Name"]));
            }
            set {
                this["D4Param3Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("t. scalzata (msec)")]
        public string D4Param4Name {
            get {
                return ((string)(this["D4Param4Name"]));
            }
            set {
                this["D4Param4Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool D4Param1On {
            get {
                return ((bool)(this["D4Param1On"]));
            }
            set {
                this["D4Param1On"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool D4Param2On {
            get {
                return ((bool)(this["D4Param2On"]));
            }
            set {
                this["D4Param2On"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool D4Param3On {
            get {
                return ((bool)(this["D4Param3On"]));
            }
            set {
                this["D4Param3On"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool D4Param4On {
            get {
                return ((bool)(this["D4Param4On"]));
            }
            set {
                this["D4Param4On"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int D4Mode {
            get {
                return ((int)(this["D4Mode"]));
            }
            set {
                this["D4Mode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool D4WithRecipe {
            get {
                return ((bool)(this["D4WithRecipe"]));
            }
            set {
                this["D4WithRecipe"] = value;
            }
        }
    }
}
