//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionLaunch.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.13.0.0")]
    internal sealed partial class GDevice2 : global::System.Configuration.ApplicationSettingsBase {
        
        private static GDevice2 defaultInstance = ((GDevice2)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new GDevice2())));
        
        public static GDevice2 Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("glue dehumidifier")]
        public string GD2Name {
            get {
                return ((string)(this["GD2Name"]));
            }
            set {
                this["GD2Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool GD2Present {
            get {
                return ((bool)(this["GD2Present"]));
            }
            set {
                this["GD2Present"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("working T. (°C)")]
        public string GD2Param1Name {
            get {
                return ((string)(this["GD2Param1Name"]));
            }
            set {
                this["GD2Param1Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("maintenance T. (°)")]
        public string GD2Param2Name {
            get {
                return ((string)(this["GD2Param2Name"]));
            }
            set {
                this["GD2Param2Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GD2Param3Name {
            get {
                return ((string)(this["GD2Param3Name"]));
            }
            set {
                this["GD2Param3Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GD2Param4Name {
            get {
                return ((string)(this["GD2Param4Name"]));
            }
            set {
                this["GD2Param4Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GD2Param5Name {
            get {
                return ((string)(this["GD2Param5Name"]));
            }
            set {
                this["GD2Param5Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GD2Param6Name {
            get {
                return ((string)(this["GD2Param6Name"]));
            }
            set {
                this["GD2Param6Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("pallet release (sec)")]
        public string GD2Param7Name {
            get {
                return ((string)(this["GD2Param7Name"]));
            }
            set {
                this["GD2Param7Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool GD2Param1IsOn {
            get {
                return ((bool)(this["GD2Param1IsOn"]));
            }
            set {
                this["GD2Param1IsOn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool GD2Param2IsOn {
            get {
                return ((bool)(this["GD2Param2IsOn"]));
            }
            set {
                this["GD2Param2IsOn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool GD2Param3IsOn {
            get {
                return ((bool)(this["GD2Param3IsOn"]));
            }
            set {
                this["GD2Param3IsOn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool GD2Param4IsOn {
            get {
                return ((bool)(this["GD2Param4IsOn"]));
            }
            set {
                this["GD2Param4IsOn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool GD2Param5IsOn {
            get {
                return ((bool)(this["GD2Param5IsOn"]));
            }
            set {
                this["GD2Param5IsOn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool GD2Param6IsOn {
            get {
                return ((bool)(this["GD2Param6IsOn"]));
            }
            set {
                this["GD2Param6IsOn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool GD2Param7IsOn {
            get {
                return ((bool)(this["GD2Param7IsOn"]));
            }
            set {
                this["GD2Param7IsOn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("heating camera T. (°C)")]
        public string GD2Runtime1Name {
            get {
                return ((string)(this["GD2Runtime1Name"]));
            }
            set {
                this["GD2Runtime1Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("cooling camera T. (°C)")]
        public string GD2Runtime2Name {
            get {
                return ((string)(this["GD2Runtime2Name"]));
            }
            set {
                this["GD2Runtime2Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("humidity (%)")]
        public string GD2Runtime3Name {
            get {
                return ((string)(this["GD2Runtime3Name"]));
            }
            set {
                this["GD2Runtime3Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("runtime camera T. (°C)")]
        public string GD2Runtime4Name {
            get {
                return ((string)(this["GD2Runtime4Name"]));
            }
            set {
                this["GD2Runtime4Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool GD2Runtime1IsOn {
            get {
                return ((bool)(this["GD2Runtime1IsOn"]));
            }
            set {
                this["GD2Runtime1IsOn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool GD2Runtime2IsOn {
            get {
                return ((bool)(this["GD2Runtime2IsOn"]));
            }
            set {
                this["GD2Runtime2IsOn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool GD2Runtime3IsOn {
            get {
                return ((bool)(this["GD2Runtime3IsOn"]));
            }
            set {
                this["GD2Runtime3IsOn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool GD2Runtime4IsOn {
            get {
                return ((bool)(this["GD2Runtime4IsOn"]));
            }
            set {
                this["GD2Runtime4IsOn"] = value;
            }
        }
    }
}
