//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionLaunch.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.12.0.0")]
    internal sealed partial class GDevice1 : global::System.Configuration.ApplicationSettingsBase {
        
        private static GDevice1 defaultInstance = ((GDevice1)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new GDevice1())));
        
        public static GDevice1 Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("scale")]
        public string GD1Name {
            get {
                return ((string)(this["GD1Name"]));
            }
            set {
                this["GD1Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool GD1Present {
            get {
                return ((bool)(this["GD1Present"]));
            }
            set {
                this["GD1Present"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("almost empty level (gr)")]
        public string GD1Param1Name {
            get {
                return ((string)(this["GD1Param1Name"]));
            }
            set {
                this["GD1Param1Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("empty level (gr)")]
        public string GD1Param2Name {
            get {
                return ((string)(this["GD1Param2Name"]));
            }
            set {
                this["GD1Param2Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GD1Param3Name {
            get {
                return ((string)(this["GD1Param3Name"]));
            }
            set {
                this["GD1Param3Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GD1Param4Name {
            get {
                return ((string)(this["GD1Param4Name"]));
            }
            set {
                this["GD1Param4Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GD1Param5Name {
            get {
                return ((string)(this["GD1Param5Name"]));
            }
            set {
                this["GD1Param5Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GD1Param6Name {
            get {
                return ((string)(this["GD1Param6Name"]));
            }
            set {
                this["GD1Param6Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GD1Param7Name {
            get {
                return ((string)(this["GD1Param7Name"]));
            }
            set {
                this["GD1Param7Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool GD1Param1IsOn {
            get {
                return ((bool)(this["GD1Param1IsOn"]));
            }
            set {
                this["GD1Param1IsOn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool GD1Param2IsOn {
            get {
                return ((bool)(this["GD1Param2IsOn"]));
            }
            set {
                this["GD1Param2IsOn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool GD1Param3IsOn {
            get {
                return ((bool)(this["GD1Param3IsOn"]));
            }
            set {
                this["GD1Param3IsOn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool GD1Param4IsOn {
            get {
                return ((bool)(this["GD1Param4IsOn"]));
            }
            set {
                this["GD1Param4IsOn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool GD1Param5IsOn {
            get {
                return ((bool)(this["GD1Param5IsOn"]));
            }
            set {
                this["GD1Param5IsOn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool GD1Param6IsOn {
            get {
                return ((bool)(this["GD1Param6IsOn"]));
            }
            set {
                this["GD1Param6IsOn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool GD1Param7IsOn {
            get {
                return ((bool)(this["GD1Param7IsOn"]));
            }
            set {
                this["GD1Param7IsOn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("gross weight (gr)")]
        public string GD1Runtime1Name {
            get {
                return ((string)(this["GD1Runtime1Name"]));
            }
            set {
                this["GD1Runtime1Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("net weight (gr)")]
        public string GD1Runtime2Name {
            get {
                return ((string)(this["GD1Runtime2Name"]));
            }
            set {
                this["GD1Runtime2Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GD1Runtime3Name {
            get {
                return ((string)(this["GD1Runtime3Name"]));
            }
            set {
                this["GD1Runtime3Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GD1Runtime4Name {
            get {
                return ((string)(this["GD1Runtime4Name"]));
            }
            set {
                this["GD1Runtime4Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool GD1Runtime1IsOn {
            get {
                return ((bool)(this["GD1Runtime1IsOn"]));
            }
            set {
                this["GD1Runtime1IsOn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool GD1Runtime2IsOn {
            get {
                return ((bool)(this["GD1Runtime2IsOn"]));
            }
            set {
                this["GD1Runtime2IsOn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool GD1Runtime3IsOn {
            get {
                return ((bool)(this["GD1Runtime3IsOn"]));
            }
            set {
                this["GD1Runtime3IsOn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool GD1Runtime4IsOn {
            get {
                return ((bool)(this["GD1Runtime4IsOn"]));
            }
            set {
                this["GD1Runtime4IsOn"] = value;
            }
        }
    }
}
