//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionLaunch.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.12.0.0")]
    internal sealed partial class R2 : global::System.Configuration.ApplicationSettingsBase {
        
        private static R2 defaultInstance = ((R2)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new R2())));
        
        public static R2 Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool R2Present {
            get {
                return ((bool)(this["R2Present"]));
            }
            set {
                this["R2Present"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int R2Mode {
            get {
                return ((int)(this["R2Mode"]));
            }
            set {
                this["R2Mode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("glue robot")]
        public string R2Name {
            get {
                return ((string)(this["R2Name"]));
            }
            set {
                this["R2Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("central line")]
        public string R2Lav {
            get {
                return ((string)(this["R2Lav"]));
            }
            set {
                this["R2Lav"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("contour")]
        public string R2Au1 {
            get {
                return ((string)(this["R2Au1"]));
            }
            set {
                this["R2Au1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("inside contour")]
        public string R2Au2 {
            get {
                return ((string)(this["R2Au2"]));
            }
            set {
                this["R2Au2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int InputNumber {
            get {
                return ((int)(this["InputNumber"]));
            }
            set {
                this["InputNumber"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int OutputNumber {
            get {
                return ((int)(this["OutputNumber"]));
            }
            set {
                this["OutputNumber"] = value;
            }
        }
    }
}
