//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionLaunch.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.12.0.0")]
    internal sealed partial class R3 : global::System.Configuration.ApplicationSettingsBase {
        
        private static R3 defaultInstance = ((R3)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new R3())));
        
        public static R3 Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool R3Present {
            get {
                return ((bool)(this["R3Present"]));
            }
            set {
                this["R3Present"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int R3Mode {
            get {
                return ((int)(this["R3Mode"]));
            }
            set {
                this["R3Mode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("scanner")]
        public string R3Name {
            get {
                return ((string)(this["R3Name"]));
            }
            set {
                this["R3Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("bottom brush")]
        public string R3Lav {
            get {
                return ((string)(this["R3Lav"]));
            }
            set {
                this["R3Lav"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("side brush")]
        public string R3Au1 {
            get {
                return ((string)(this["R3Au1"]));
            }
            set {
                this["R3Au1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("bottom paintbrush")]
        public string R3Au2 {
            get {
                return ((string)(this["R3Au2"]));
            }
            set {
                this["R3Au2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int InputNumber {
            get {
                return ((int)(this["InputNumber"]));
            }
            set {
                this["InputNumber"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int OutputNumber {
            get {
                return ((int)(this["OutputNumber"]));
            }
            set {
                this["OutputNumber"] = value;
            }
        }
    }
}
