//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionLaunch.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.2.0.0")]
    internal sealed partial class SettingsKAWASAKI : global::System.Configuration.ApplicationSettingsBase {
        
        private static SettingsKAWASAKI defaultInstance = ((SettingsKAWASAKI)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new SettingsKAWASAKI())));
        
        public static SettingsKAWASAKI Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool krcdllIsPresent {
            get {
                return ((bool)(this["krcdllIsPresent"]));
            }
            set {
                this["krcdllIsPresent"] = value;
            }
        }
    }
}
