//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionLaunch.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.12.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("it-IT")]
        public string language {
            get {
                return ((string)(this["language"]));
            }
            set {
                this["language"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("340")]
        public short beginSize {
            get {
                return ((short)(this["beginSize"]));
            }
            set {
                this["beginSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("420")]
        public short endSize {
            get {
                return ((short)(this["endSize"]));
            }
            set {
                this["endSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public short stepSize {
            get {
                return ((short)(this["stepSize"]));
            }
            set {
                this["stepSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool modelNameR1Aux0_00 {
            get {
                return ((bool)(this["modelNameR1Aux0_00"]));
            }
            set {
                this["modelNameR1Aux0_00"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool modelNameR1Aux1_00 {
            get {
                return ((bool)(this["modelNameR1Aux1_00"]));
            }
            set {
                this["modelNameR1Aux1_00"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool modelNameR1Aux2_00 {
            get {
                return ((bool)(this["modelNameR1Aux2_00"]));
            }
            set {
                this["modelNameR1Aux2_00"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool modelNameR1Aux0_01 {
            get {
                return ((bool)(this["modelNameR1Aux0_01"]));
            }
            set {
                this["modelNameR1Aux0_01"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool modelNameR1Aux1_01 {
            get {
                return ((bool)(this["modelNameR1Aux1_01"]));
            }
            set {
                this["modelNameR1Aux1_01"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool modelNameR1Aux2_01 {
            get {
                return ((bool)(this["modelNameR1Aux2_01"]));
            }
            set {
                this["modelNameR1Aux2_01"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool modelNameR2Aux0_00 {
            get {
                return ((bool)(this["modelNameR2Aux0_00"]));
            }
            set {
                this["modelNameR2Aux0_00"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool modelNameR2Aux1_00 {
            get {
                return ((bool)(this["modelNameR2Aux1_00"]));
            }
            set {
                this["modelNameR2Aux1_00"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool modelNameR2Aux2_00 {
            get {
                return ((bool)(this["modelNameR2Aux2_00"]));
            }
            set {
                this["modelNameR2Aux2_00"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool modelNameR2Aux0_01 {
            get {
                return ((bool)(this["modelNameR2Aux0_01"]));
            }
            set {
                this["modelNameR2Aux0_01"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool modelNameR2Aux1_01 {
            get {
                return ((bool)(this["modelNameR2Aux1_01"]));
            }
            set {
                this["modelNameR2Aux1_01"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool modelNameR2Aux2_01 {
            get {
                return ((bool)(this["modelNameR2Aux2_01"]));
            }
            set {
                this["modelNameR2Aux2_01"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool modelNameR3Aux0_00 {
            get {
                return ((bool)(this["modelNameR3Aux0_00"]));
            }
            set {
                this["modelNameR3Aux0_00"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool modelNameR3Aux1_00 {
            get {
                return ((bool)(this["modelNameR3Aux1_00"]));
            }
            set {
                this["modelNameR3Aux1_00"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool modelNameR3Aux2_00 {
            get {
                return ((bool)(this["modelNameR3Aux2_00"]));
            }
            set {
                this["modelNameR3Aux2_00"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool modelNameR3Aux0_01 {
            get {
                return ((bool)(this["modelNameR3Aux0_01"]));
            }
            set {
                this["modelNameR3Aux0_01"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool modelNameR3Aux1_01 {
            get {
                return ((bool)(this["modelNameR3Aux1_01"]));
            }
            set {
                this["modelNameR3Aux1_01"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool modelNameR3Aux2_01 {
            get {
                return ((bool)(this["modelNameR3Aux2_01"]));
            }
            set {
                this["modelNameR3Aux2_01"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("robots")]
        public string loginPassword {
            get {
                return ((string)(this["loginPassword"]));
            }
            set {
                this["loginPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("user")]
        public string loginLevel {
            get {
                return ((string)(this["loginLevel"]));
            }
            set {
                this["loginLevel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("18")]
        public string modelNameFlagNumber {
            get {
                return ((string)(this["modelNameFlagNumber"]));
            }
            set {
                this["modelNameFlagNumber"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("172.31.10.136")]
        public string localHostIPAddress {
            get {
                return ((string)(this["localHostIPAddress"]));
            }
            set {
                this["localHostIPAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("32769")]
        public string localHostPortNumber {
            get {
                return ((string)(this["localHostPortNumber"]));
            }
            set {
                this["localHostPortNumber"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BALLUFF")]
        public string readerType {
            get {
                return ((string)(this["readerType"]));
            }
            set {
                this["readerType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00,01,02,03,04,05,06,07,08,09,10,11,12,TC,CA,BE,PA,VE,TS,PE")]
        public string variantList {
            get {
                return ((string)(this["variantList"]));
            }
            set {
                this["variantList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsRemoteAssociation {
            get {
                return ((bool)(this["IsRemoteAssociation"]));
            }
            set {
                this["IsRemoteAssociation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool modelNameR4Aux0_00 {
            get {
                return ((bool)(this["modelNameR4Aux0_00"]));
            }
            set {
                this["modelNameR4Aux0_00"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool modelNameR4Aux1_00 {
            get {
                return ((bool)(this["modelNameR4Aux1_00"]));
            }
            set {
                this["modelNameR4Aux1_00"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool modelNameR4Aux2_00 {
            get {
                return ((bool)(this["modelNameR4Aux2_00"]));
            }
            set {
                this["modelNameR4Aux2_00"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool modelNameR4Aux0_01 {
            get {
                return ((bool)(this["modelNameR4Aux0_01"]));
            }
            set {
                this["modelNameR4Aux0_01"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool modelNameR4Aux1_01 {
            get {
                return ((bool)(this["modelNameR4Aux1_01"]));
            }
            set {
                this["modelNameR4Aux1_01"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool modelNameR4Aux2_01 {
            get {
                return ((bool)(this["modelNameR4Aux2_01"]));
            }
            set {
                this["modelNameR4Aux2_01"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Robotsys\\PL\\CSharp\\images\\splash_screen.png")]
        public string SplashScreenFilepath {
            get {
                return ((string)(this["SplashScreenFilepath"]));
            }
            set {
                this["SplashScreenFilepath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("opc.tcp://172.31.20.5:4840")]
        public string OpcClient_1_URI {
            get {
                return ((string)(this["OpcClient_1_URI"]));
            }
            set {
                this["OpcClient_1_URI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("128")]
        public ushort AlarmsNumber {
            get {
                return ((ushort)(this["AlarmsNumber"]));
            }
            set {
                this["AlarmsNumber"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int LinePLCInputNumber {
            get {
                return ((int)(this["LinePLCInputNumber"]));
            }
            set {
                this["LinePLCInputNumber"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int LinePLCOutputNumber {
            get {
                return ((int)(this["LinePLCOutputNumber"]));
            }
            set {
                this["LinePLCOutputNumber"] = value;
            }
        }
    }
}
