//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionLaunch.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.12.0.0")]
    internal sealed partial class SettingsFilesPath : global::System.Configuration.ApplicationSettingsBase {
        
        private static SettingsFilesPath defaultInstance = ((SettingsFilesPath)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new SettingsFilesPath())));
        
        public static SettingsFilesPath Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\PRODUCTION\\Programs\\R1")]
        public string r1FilenamePath {
            get {
                return ((string)(this["r1FilenamePath"]));
            }
            set {
                this["r1FilenamePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\PRODUCTION\\Programs\\R2")]
        public string r2FilenamePath {
            get {
                return ((string)(this["r2FilenamePath"]));
            }
            set {
                this["r2FilenamePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\PRODUCTION\\Programs\\R3")]
        public string r3FilenamePath {
            get {
                return ((string)(this["r3FilenamePath"]));
            }
            set {
                this["r3FilenamePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\PRODUCTION\\Programs\\cement")]
        public string r4FilenamePath {
            get {
                return ((string)(this["r4FilenamePath"]));
            }
            set {
                this["r4FilenamePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\srvfs2.roveda.internal\\Linee_Robotizzate\\Chanel\\Notes")]
        public string notesPath {
            get {
                return ((string)(this["notesPath"]));
            }
            set {
                this["notesPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\172.31.10.146\\PRODUCTION\\DB\\DB_Production.mdb")]
        public string dbRemotePath1 {
            get {
                return ((string)(this["dbRemotePath1"]));
            }
            set {
                this["dbRemotePath1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\172.31.10.166\\PRODUCTION\\DB\\DB_Production.mdb")]
        public string dbRemotePath2 {
            get {
                return ((string)(this["dbRemotePath2"]));
            }
            set {
                this["dbRemotePath2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\172.31.10.156\\PRODUCTION\\DB\\DB_Production.mdb")]
        public string dbRemotePath3 {
            get {
                return ((string)(this["dbRemotePath3"]));
            }
            set {
                this["dbRemotePath3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\172.31.10.176\\PRODUCTION\\DB\\DB_Production.mdb")]
        public string dbRemotePath4 {
            get {
                return ((string)(this["dbRemotePath4"]));
            }
            set {
                this["dbRemotePath4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\PRODUCTION\\DB\\DB_Production.mdb")]
        public string dbLocalPath {
            get {
                return ((string)(this["dbLocalPath"]));
            }
            set {
                this["dbLocalPath"] = value;
            }
        }
    }
}
