//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionLaunch.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.2.0.0")]
    internal sealed partial class SettingsDB : global::System.Configuration.ApplicationSettingsBase {
        
        private static SettingsDB defaultInstance = ((SettingsDB)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new SettingsDB())));
        
        public static SettingsDB Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("rfid_code")]
        public string rfidTableName {
            get {
                return ((string)(this["rfidTableName"]));
            }
            set {
                this["rfidTableName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Codice_Tag")]
        public string rfidCodeFieldName {
            get {
                return ((string)(this["rfidCodeFieldName"]));
            }
            set {
                this["rfidCodeFieldName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Numero")]
        public string rfidSizeFieldName {
            get {
                return ((string)(this["rfidSizeFieldName"]));
            }
            set {
                this["rfidSizeFieldName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tipo")]
        public string rfidTypeFieldName {
            get {
                return ((string)(this["rfidTypeFieldName"]));
            }
            set {
                this["rfidTypeFieldName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Codice")]
        public string rfidRobotCodeFieldName {
            get {
                return ((string)(this["rfidRobotCodeFieldName"]));
            }
            set {
                this["rfidRobotCodeFieldName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("archive")]
        public string archiveR1TableName {
            get {
                return ((string)(this["archiveR1TableName"]));
            }
            set {
                this["archiveR1TableName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("archive")]
        public string archiveR2TableName {
            get {
                return ((string)(this["archiveR2TableName"]));
            }
            set {
                this["archiveR2TableName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("archive")]
        public string archiveR3TableName {
            get {
                return ((string)(this["archiveR3TableName"]));
            }
            set {
                this["archiveR3TableName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("archive")]
        public string archiveR4TableName {
            get {
                return ((string)(this["archiveR4TableName"]));
            }
            set {
                this["archiveR4TableName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Codice")]
        public string archiveCodeFieldName {
            get {
                return ((string)(this["archiveCodeFieldName"]));
            }
            set {
                this["archiveCodeFieldName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Fl_Aux0")]
        public string archiveAux0FieldName {
            get {
                return ((string)(this["archiveAux0FieldName"]));
            }
            set {
                this["archiveAux0FieldName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Fl_Aux1")]
        public string archiveAux1FieldName {
            get {
                return ((string)(this["archiveAux1FieldName"]));
            }
            set {
                this["archiveAux1FieldName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Fl_Aux2")]
        public string archiveAux2FieldName {
            get {
                return ((string)(this["archiveAux2FieldName"]));
            }
            set {
                this["archiveAux2FieldName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Fl_Aux3")]
        public string archiveAux3FieldName {
            get {
                return ((string)(this["archiveAux3FieldName"]));
            }
            set {
                this["archiveAux3FieldName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("model_name")]
        public string modelTableName {
            get {
                return ((string)(this["modelTableName"]));
            }
            set {
                this["modelTableName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Codice")]
        public string modelCodeField {
            get {
                return ((string)(this["modelCodeField"]));
            }
            set {
                this["modelCodeField"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("lav_00")]
        public string modelR1FieldNameAux0_00 {
            get {
                return ((string)(this["modelR1FieldNameAux0_00"]));
            }
            set {
                this["modelR1FieldNameAux0_00"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("au1_00")]
        public string modelR1FieldNameAux1_00 {
            get {
                return ((string)(this["modelR1FieldNameAux1_00"]));
            }
            set {
                this["modelR1FieldNameAux1_00"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("au2_00")]
        public string modelR1FieldNameAux2_00 {
            get {
                return ((string)(this["modelR1FieldNameAux2_00"]));
            }
            set {
                this["modelR1FieldNameAux2_00"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("lav_01")]
        public string modelR1FieldNameAux0_01 {
            get {
                return ((string)(this["modelR1FieldNameAux0_01"]));
            }
            set {
                this["modelR1FieldNameAux0_01"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("au1_01")]
        public string modelR1FieldNameAux1_01 {
            get {
                return ((string)(this["modelR1FieldNameAux1_01"]));
            }
            set {
                this["modelR1FieldNameAux1_01"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("au2_01")]
        public string modelR1FieldNameAux2_01 {
            get {
                return ((string)(this["modelR1FieldNameAux2_01"]));
            }
            set {
                this["modelR1FieldNameAux2_01"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("lav_02")]
        public string modelR2FieldNameAux0_00 {
            get {
                return ((string)(this["modelR2FieldNameAux0_00"]));
            }
            set {
                this["modelR2FieldNameAux0_00"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("au1_02")]
        public string modelR2FieldNameAux1_00 {
            get {
                return ((string)(this["modelR2FieldNameAux1_00"]));
            }
            set {
                this["modelR2FieldNameAux1_00"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("au2_02")]
        public string modelR2FieldNameAux2_00 {
            get {
                return ((string)(this["modelR2FieldNameAux2_00"]));
            }
            set {
                this["modelR2FieldNameAux2_00"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("lav_03")]
        public string modelR2FieldNameAux0_01 {
            get {
                return ((string)(this["modelR2FieldNameAux0_01"]));
            }
            set {
                this["modelR2FieldNameAux0_01"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("au1_03")]
        public string modelR2FieldNameAux1_01 {
            get {
                return ((string)(this["modelR2FieldNameAux1_01"]));
            }
            set {
                this["modelR2FieldNameAux1_01"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("au2_03")]
        public string modelR2FieldNameAux2_01 {
            get {
                return ((string)(this["modelR2FieldNameAux2_01"]));
            }
            set {
                this["modelR2FieldNameAux2_01"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("lav_04")]
        public string modelR3FieldNameAux0_00 {
            get {
                return ((string)(this["modelR3FieldNameAux0_00"]));
            }
            set {
                this["modelR3FieldNameAux0_00"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("au1_04")]
        public string modelR3FieldNameAux1_00 {
            get {
                return ((string)(this["modelR3FieldNameAux1_00"]));
            }
            set {
                this["modelR3FieldNameAux1_00"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("au2_04")]
        public string modelR3FieldNameAux2_00 {
            get {
                return ((string)(this["modelR3FieldNameAux2_00"]));
            }
            set {
                this["modelR3FieldNameAux2_00"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("lav_05")]
        public string modelR3FieldNameAux0_01 {
            get {
                return ((string)(this["modelR3FieldNameAux0_01"]));
            }
            set {
                this["modelR3FieldNameAux0_01"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("au1_05")]
        public string modelR3FieldNameAux1_01 {
            get {
                return ((string)(this["modelR3FieldNameAux1_01"]));
            }
            set {
                this["modelR3FieldNameAux1_01"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("au2_05")]
        public string modelR3FieldNameAux2_01 {
            get {
                return ((string)(this["modelR3FieldNameAux2_01"]));
            }
            set {
                this["modelR3FieldNameAux2_01"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("lav_06")]
        public string modelR4FieldNameAux0_00 {
            get {
                return ((string)(this["modelR4FieldNameAux0_00"]));
            }
            set {
                this["modelR4FieldNameAux0_00"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("au1_06")]
        public string modelR4FieldNameAux1_00 {
            get {
                return ((string)(this["modelR4FieldNameAux1_00"]));
            }
            set {
                this["modelR4FieldNameAux1_00"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("au2_06")]
        public string modelR4FieldNameAux2_00 {
            get {
                return ((string)(this["modelR4FieldNameAux2_00"]));
            }
            set {
                this["modelR4FieldNameAux2_00"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("lav_07")]
        public string modelR4FieldNameAux0_01 {
            get {
                return ((string)(this["modelR4FieldNameAux0_01"]));
            }
            set {
                this["modelR4FieldNameAux0_01"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("au1_07")]
        public string modelR4FieldNameAux1_01 {
            get {
                return ((string)(this["modelR4FieldNameAux1_01"]));
            }
            set {
                this["modelR4FieldNameAux1_01"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("au2_07")]
        public string modelR4FieldNameAux2_01 {
            get {
                return ((string)(this["modelR4FieldNameAux2_01"]));
            }
            set {
                this["modelR4FieldNameAux2_01"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("notes")]
        public string noteTableName {
            get {
                return ((string)(this["noteTableName"]));
            }
            set {
                this["noteTableName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("code")]
        public string noteCodeFieldName {
            get {
                return ((string)(this["noteCodeFieldName"]));
            }
            set {
                this["noteCodeFieldName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("model_name")]
        public string noteRobotCodeFieldName {
            get {
                return ((string)(this["noteRobotCodeFieldName"]));
            }
            set {
                this["noteRobotCodeFieldName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("article_name")]
        public string noteArticleFieldName {
            get {
                return ((string)(this["noteArticleFieldName"]));
            }
            set {
                this["noteArticleFieldName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("target_numbered")]
        public string noteTargetNumberedFieldName {
            get {
                return ((string)(this["noteTargetNumberedFieldName"]));
            }
            set {
                this["noteTargetNumberedFieldName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("done_numbered")]
        public string noteDoneNumberedFieldName {
            get {
                return ((string)(this["noteDoneNumberedFieldName"]));
            }
            set {
                this["noteDoneNumberedFieldName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("loaded_numbered")]
        public string noteLoadedNumberedFieldName {
            get {
                return ((string)(this["noteLoadedNumberedFieldName"]));
            }
            set {
                this["noteLoadedNumberedFieldName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("param1")]
        public string noteCustom1FieldName {
            get {
                return ((string)(this["noteCustom1FieldName"]));
            }
            set {
                this["noteCustom1FieldName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("param2")]
        public string noteCustom2FieldName {
            get {
                return ((string)(this["noteCustom2FieldName"]));
            }
            set {
                this["noteCustom2FieldName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("barcode")]
        public string rfidNoteFieldName {
            get {
                return ((string)(this["rfidNoteFieldName"]));
            }
            set {
                this["rfidNoteFieldName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Doppione")]
        public string rfidVariantFieldName {
            get {
                return ((string)(this["rfidVariantFieldName"]));
            }
            set {
                this["rfidVariantFieldName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("status")]
        public string rfidStatusFieldName {
            get {
                return ((string)(this["rfidStatusFieldName"]));
            }
            set {
                this["rfidStatusFieldName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("param1")]
        public string rfidParam1FieldName {
            get {
                return ((string)(this["rfidParam1FieldName"]));
            }
            set {
                this["rfidParam1FieldName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("param2")]
        public string rfidParam2FieldName {
            get {
                return ((string)(this["rfidParam2FieldName"]));
            }
            set {
                this["rfidParam2FieldName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("recipe_D1")]
        public string recipeD1TableName {
            get {
                return ((string)(this["recipeD1TableName"]));
            }
            set {
                this["recipeD1TableName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("recipe_D2")]
        public string recipeD2TableName {
            get {
                return ((string)(this["recipeD2TableName"]));
            }
            set {
                this["recipeD2TableName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("recipe_D3")]
        public string recipeD3TableName {
            get {
                return ((string)(this["recipeD3TableName"]));
            }
            set {
                this["recipeD3TableName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("recipe_code")]
        public string recipeD1CodeFieldName {
            get {
                return ((string)(this["recipeD1CodeFieldName"]));
            }
            set {
                this["recipeD1CodeFieldName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("recipe_code")]
        public string recipeD2CodeFieldName {
            get {
                return ((string)(this["recipeD2CodeFieldName"]));
            }
            set {
                this["recipeD2CodeFieldName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("recipe_code")]
        public string recipeD3CodeFieldName {
            get {
                return ((string)(this["recipeD3CodeFieldName"]));
            }
            set {
                this["recipeD3CodeFieldName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("param1")]
        public string recipeD1Param1FieldName {
            get {
                return ((string)(this["recipeD1Param1FieldName"]));
            }
            set {
                this["recipeD1Param1FieldName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("param2")]
        public string recipeD1Param2FieldName {
            get {
                return ((string)(this["recipeD1Param2FieldName"]));
            }
            set {
                this["recipeD1Param2FieldName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("param3")]
        public string recipeD1Param3FieldName {
            get {
                return ((string)(this["recipeD1Param3FieldName"]));
            }
            set {
                this["recipeD1Param3FieldName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("param1")]
        public string recipeD2Param1FieldName {
            get {
                return ((string)(this["recipeD2Param1FieldName"]));
            }
            set {
                this["recipeD2Param1FieldName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("param2")]
        public string recipeD2Param2FieldName {
            get {
                return ((string)(this["recipeD2Param2FieldName"]));
            }
            set {
                this["recipeD2Param2FieldName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("param3")]
        public string recipeD2Param3FieldName {
            get {
                return ((string)(this["recipeD2Param3FieldName"]));
            }
            set {
                this["recipeD2Param3FieldName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("param1")]
        public string recipeD3Param1FieldName {
            get {
                return ((string)(this["recipeD3Param1FieldName"]));
            }
            set {
                this["recipeD3Param1FieldName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("param2")]
        public string recipeD3Param2FieldName {
            get {
                return ((string)(this["recipeD3Param2FieldName"]));
            }
            set {
                this["recipeD3Param2FieldName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("param3")]
        public string recipeD3Param3FieldName {
            get {
                return ((string)(this["recipeD3Param3FieldName"]));
            }
            set {
                this["recipeD3Param3FieldName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("param1")]
        public string noteParam1FieldName {
            get {
                return ((string)(this["noteParam1FieldName"]));
            }
            set {
                this["noteParam1FieldName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("param2")]
        public string noteParam2FieldName {
            get {
                return ((string)(this["noteParam2FieldName"]));
            }
            set {
                this["noteParam2FieldName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("param4")]
        public string recipeD1Param4FieldName {
            get {
                return ((string)(this["recipeD1Param4FieldName"]));
            }
            set {
                this["recipeD1Param4FieldName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("param4")]
        public string recipeD2Param4FieldName {
            get {
                return ((string)(this["recipeD2Param4FieldName"]));
            }
            set {
                this["recipeD2Param4FieldName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("param4")]
        public string recipeD3Param4FieldName {
            get {
                return ((string)(this["recipeD3Param4FieldName"]));
            }
            set {
                this["recipeD3Param4FieldName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("param4")]
        public string recipeD4Param4FieldName {
            get {
                return ((string)(this["recipeD4Param4FieldName"]));
            }
            set {
                this["recipeD4Param4FieldName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("recipe_code")]
        public string recipeD4CodeFieldName {
            get {
                return ((string)(this["recipeD4CodeFieldName"]));
            }
            set {
                this["recipeD4CodeFieldName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("recipe_D4")]
        public string recipeD4TableName {
            get {
                return ((string)(this["recipeD4TableName"]));
            }
            set {
                this["recipeD4TableName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("param1")]
        public string recipeD4Param1FieldName {
            get {
                return ((string)(this["recipeD4Param1FieldName"]));
            }
            set {
                this["recipeD4Param1FieldName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("param2")]
        public string recipeD4Param2FieldName {
            get {
                return ((string)(this["recipeD4Param2FieldName"]));
            }
            set {
                this["recipeD4Param2FieldName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("param3")]
        public string recipeD4Param3FieldName {
            get {
                return ((string)(this["recipeD4Param3FieldName"]));
            }
            set {
                this["recipeD4Param3FieldName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("param3")]
        public string rfidParam3FieldName {
            get {
                return ((string)(this["rfidParam3FieldName"]));
            }
            set {
                this["rfidParam3FieldName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("param3")]
        public string noteCustom3FieldName {
            get {
                return ((string)(this["noteCustom3FieldName"]));
            }
            set {
                this["noteCustom3FieldName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("param4")]
        public string noteCustom4FieldName {
            get {
                return ((string)(this["noteCustom4FieldName"]));
            }
            set {
                this["noteCustom4FieldName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("param5")]
        public string noteCustom5FieldName {
            get {
                return ((string)(this["noteCustom5FieldName"]));
            }
            set {
                this["noteCustom5FieldName"] = value;
            }
        }
    }
}
