//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionLaunch.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.12.0.0")]
    internal sealed partial class Simulation : global::System.Configuration.ApplicationSettingsBase {
        
        private static Simulation defaultInstance = ((Simulation)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Simulation())));
        
        public static Simulation Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool rfidG1Simulation {
            get {
                return ((bool)(this["rfidG1Simulation"]));
            }
            set {
                this["rfidG1Simulation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool R1Simulation {
            get {
                return ((bool)(this["R1Simulation"]));
            }
            set {
                this["R1Simulation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool R2Simulation {
            get {
                return ((bool)(this["R2Simulation"]));
            }
            set {
                this["R2Simulation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool R3Simulation {
            get {
                return ((bool)(this["R3Simulation"]));
            }
            set {
                this["R3Simulation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool R4Simulation {
            get {
                return ((bool)(this["R4Simulation"]));
            }
            set {
                this["R4Simulation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool rfidG2Simulation {
            get {
                return ((bool)(this["rfidG2Simulation"]));
            }
            set {
                this["rfidG2Simulation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool rfidG3Simulation {
            get {
                return ((bool)(this["rfidG3Simulation"]));
            }
            set {
                this["rfidG3Simulation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool rfidG4Simulation {
            get {
                return ((bool)(this["rfidG4Simulation"]));
            }
            set {
                this["rfidG4Simulation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool rfidG5Simulation {
            get {
                return ((bool)(this["rfidG5Simulation"]));
            }
            set {
                this["rfidG5Simulation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool G1A1ReadingRequestSimulation {
            get {
                return ((bool)(this["G1A1ReadingRequestSimulation"]));
            }
            set {
                this["G1A1ReadingRequestSimulation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool G1A2ReadingRequestSimulation {
            get {
                return ((bool)(this["G1A2ReadingRequestSimulation"]));
            }
            set {
                this["G1A2ReadingRequestSimulation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool G1A3ReadingRequestSimulation {
            get {
                return ((bool)(this["G1A3ReadingRequestSimulation"]));
            }
            set {
                this["G1A3ReadingRequestSimulation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool G1A4ReadingRequestSimulation {
            get {
                return ((bool)(this["G1A4ReadingRequestSimulation"]));
            }
            set {
                this["G1A4ReadingRequestSimulation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool G2A1ReadingRequestSimulation {
            get {
                return ((bool)(this["G2A1ReadingRequestSimulation"]));
            }
            set {
                this["G2A1ReadingRequestSimulation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool G2A2ReadingRequestSimulation {
            get {
                return ((bool)(this["G2A2ReadingRequestSimulation"]));
            }
            set {
                this["G2A2ReadingRequestSimulation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool G3A1ReadingRequestSimulation {
            get {
                return ((bool)(this["G3A1ReadingRequestSimulation"]));
            }
            set {
                this["G3A1ReadingRequestSimulation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool G3A2ReadingRequestSimulation {
            get {
                return ((bool)(this["G3A2ReadingRequestSimulation"]));
            }
            set {
                this["G3A2ReadingRequestSimulation"] = value;
            }
        }
    }
}
